### PR TITLE
Automatic delta time functionality

### PR DESCRIPTION
**Pull request by rcarson3**
Found that for a few applications that having even a rudimentary automatic delta time stepper is super useful. So, I  added something basic.

This has a test now added and have added documentation within the options.toml file that directly documents how the auto time stepping algorithm works.

### CODE REVIEW

**Comment by rcarson3** [comment]
Should pull this in after #42 is merged in

**Comment by rcarson3** [comment]
@Leonidas-Z does the options.toml description of things make sense to you? If not is there anything I could do to better describe things? I will mention that I've tested it for a wide range of parameters that were causing you issues and it seems to work pretty well.

Also, would you find it useful to be able to specify the name of the dt output file as it's currently called `auto_dt_out.txt`?

If things look alright to you I'll go ahead and merge this in after I bring in the light-up PR which will be later today.

**Comment by Leonidas-Z** [comment]
@rcarson3 That is an amazing feature that is extremely helpful! I did read the `options.toml` and I am little bit confused on the description at this part: `# dt_scaling = n_newton_iteration_taken / n_newton_iteration_val`. Shouldn't be `# dt_scaling = n_newton_iteration_val  / n_newton_iteration_taken`? 

About the name, yes it might be necessary to generate multiple `auto_dt_out.txt` files with different names since we might run different simulations simultaneously with the CP optimization framework. 

Finally, with the auto dt time option selected, we won't know the custom_dt.txt files since they will be generated after the simulations. In order to get the objective functions, it is necessary to have similar experiment points (stress, strain) to the ones that are used to generate the simulation output. That makes it necessary to implement the script [https://github.com/LeonidasZ/ExaConstit_CP_Framework/blob/main/Exaopt_DEAP/Smooth_SS_generator/Smoothening_SS_data.py](url), to the main optimization algorithm so to generate experiment points using the corresponding generated `auto_dt_out.txt`.

**Review by Leonidas-Z — APPROVED** [review]

**Comment by rcarson3** [comment]
> @rcarson3 That is an amazing feature that is extremely helpful! I did read the `options.toml` and I am little bit confused on the description at this part: `# dt_scaling = n_newton_iteration_taken / n_newton_iteration_val`. Shouldn't be `# dt_scaling = n_newton_iteration_val / n_newton_iteration_taken`?

So, I just doubled check and that actually is correct. I'll try and reword it a bit to make it clear that `n_newton_iteration_val` represents a static value that when our solver converges faster than that value we want to increase our dt value. If our solver takes more iterations than that value we want the dt value to decrease. 

> About the name, yes it might be necessary to generate multiple `auto_dt_out.txt` files with different names since we might run different simulations simultaneously with the CP optimization framework.

Alright, I'll add that feature.

> Finally, with the auto dt time option selected, we won't know the custom_dt.txt files since they will be generated after the simulations. In order to get the objective functions, it is necessary to have similar experiment points (stress, strain) to the ones that are used to generate the simulation output. That makes it necessary to implement the script [https://github.com/LeonidasZ/ExaConstit_CP_Framework/blob/main/Exaopt_DEAP/Smooth_SS_generator/Smoothening_SS_data.py](url), to the main optimization algorithm so to generate experiment points using the corresponding generated `auto_dt_out.txt`.

Okay, I don't think that should be something too crazy to have the experimental points automatically generated when the objective function is calculated as you've already implemented the necessary parts in that script. I'll look into tackling that as part of my updates to the optimization scripts.

**Pull request merged**
